# Generated by Django 5.0 on 2023-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nbr_ticket',
            field=models.IntegerField(default=1),
        ),
    ]
