# Generated by Django 4.2.7 on 2023-12-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_order_ordered_date_cart_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Recevoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('elem', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
