# Generated by Django 5.0 on 2023-12-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket_remove_event_codebare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='codebare',
            new_name='qr_code',
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
