# Generated by Django 5.0 on 2023-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_organisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id_user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
